[workspace]
channels = ["conda-forge", "bioconda", "schrodinger"]
name = "myenv"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.9.*"
mmseqs2 = ">=17.b804f,<18"
mcl = ">=22.282,<23"
scikit-learn-extra = ">=0.3.0,<0.4"
networkx = ">=3.2.1,<4"
pandas = ">=2.3.0,<3"
natsort = ">=8.4.0,<9"
umap-learn = ">=0.5.7,<0.6"
matplotlib = ">=3.9.4,<4"
datashader = ">=0.16.3,<0.17"
bokeh = ">=3.4.2,<4"
holoviews = ">=1.20.2,<2"
scikit-image = ">=0.24.0,<0.25"
colorcet = ">=3.1.0,<4"
biopython = ">=1.85,<2"
